### ISSUE TITLE
MSCLoader Suddenly feels like not updating.

### ISSUE THREAD

**Issue by WhyAmIUnlucky** [piotrulos/MSCModLoader#143]
![image_2022-02-25_212026](https://user-images.githubusercontent.com/100420764/155721980-28dbd26a-f78e-4373-9aad-da44ff43820e.png)
Info
[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/8141421/MSCLoader_Preloader.txt)
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/8141426/output_log.txt)

19042.1526
64Bit
MSCLoader Version 1.2.5
MscLoader can't search for update

Description
So recently MSCLoader started having problems searching for updates and it gives this message:
Error
=================
Check for new version failed with error: Unable to connect to the remote server
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 37.233.101.34:80
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at MSCPatcher.Form1..ctor()

**Comment by piotrulos** [comment]
This is not a bug, this is mostly related to your internet connection.
